{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.28-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.28-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.28-SNAPSHOT.jar",
          "size": 40400,
          "sha512": "21afe402baa112d803b90b332684ea77722566b010b4319bd97a9c297bbee3b803a2b836952865c5500e9602fdebd3da394d7eedbf0cf04f2cb34e91de094c80",
          "sha256": "a62d3ca6b6a8777e881ee7c394f1b1269271f53525c620c4df59e7ccd1be3eab",
          "sha1": "91c073a01e3a4bfc9b18207c51828e43e9c8c7d9",
          "md5": "7aaa8fdf462b48f74ad5a3f475dccfef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.28-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.28-SNAPSHOT.jar",
          "size": 40400,
          "sha512": "21afe402baa112d803b90b332684ea77722566b010b4319bd97a9c297bbee3b803a2b836952865c5500e9602fdebd3da394d7eedbf0cf04f2cb34e91de094c80",
          "sha256": "a62d3ca6b6a8777e881ee7c394f1b1269271f53525c620c4df59e7ccd1be3eab",
          "sha1": "91c073a01e3a4bfc9b18207c51828e43e9c8c7d9",
          "md5": "7aaa8fdf462b48f74ad5a3f475dccfef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.28-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.28-SNAPSHOT-sources.jar",
          "size": 29653,
          "sha512": "4613c36df5c6d1013052a2b9c0d7311d690a45537868eaee996b696a1ae16af6fb6b0164cc4c354ead9102b92877aaa6ea06535ec4ae8c4eb99fcd46fc15b4d5",
          "sha256": "2f2dcc59390838ee43284b4a93f248aaee82c9b39cc061e6b3b26ca2e8252f9f",
          "sha1": "2f5cf0569de14f3eec85e4ac59d68f45b566867f",
          "md5": "de425329bb9394fdcde90d990c7ac8a0"
        }
      ]
    }
  ]
}
