{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.51.jar",
          "url": "btwr-shared-lib-0.51.jar",
          "size": 94619,
          "sha512": "db254cd85f82f3116b02668d54a2ade1d807f7ffa7d2af6cc57e3a59bfe3c0d1d172cddf53a72f0a222a70f20580b328e24965801dd1d5bc34bdeddc46ba0fc4",
          "sha256": "765b308d9e239050207e190e1995c4e011a16fd6e897a7334ae82f8971021180",
          "sha1": "2f556eb40cdaa6915d6dd2afc68d8b961896e116",
          "md5": "e905dd5912df326105bc11842035d378"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.3+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.51.jar",
          "url": "btwr-shared-lib-0.51.jar",
          "size": 94619,
          "sha512": "db254cd85f82f3116b02668d54a2ade1d807f7ffa7d2af6cc57e3a59bfe3c0d1d172cddf53a72f0a222a70f20580b328e24965801dd1d5bc34bdeddc46ba0fc4",
          "sha256": "765b308d9e239050207e190e1995c4e011a16fd6e897a7334ae82f8971021180",
          "sha1": "2f556eb40cdaa6915d6dd2afc68d8b961896e116",
          "md5": "e905dd5912df326105bc11842035d378"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.51-sources.jar",
          "url": "btwr-shared-lib-0.51-sources.jar",
          "size": 63256,
          "sha512": "d4a3ffc8270881708328b6da36f5b7084f4706cc9871d87ff36ca46d0c9533d8f8634fc0d2cce55ea4d52504418e2bbe5a913ba2807966e01dc5010a91d49317",
          "sha256": "09d591583881cff1351430639f712914770809a804643878c53dc5b9b05d0e5a",
          "sha1": "3d88b4485337a40b640cd7f8227315eeaf7e45b5",
          "md5": "54664ffa54bf43765203a711466bdd3c"
        }
      ]
    }
  ]
}
