{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.19-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.19-SNAPSHOT.jar",
          "size": 39370,
          "sha512": "9c47217deacbb343db2e33a266057a34ce7963e41be20c2011109c9a15bcfeea4cb38f111be6b53eb9801f6c6becbb21025c71e9c743e04d1e35f7d14814defe",
          "sha256": "25eb822fcd9ed17b428234bf4ac5bfa75a52831db03f8b3f76d06720f56e5f42",
          "sha1": "b6f98ae03e7dadf33978853bb105c8e01a879c46",
          "md5": "09f074045b7cdf8a7f09104503a08f2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.19-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.19-SNAPSHOT.jar",
          "size": 39370,
          "sha512": "9c47217deacbb343db2e33a266057a34ce7963e41be20c2011109c9a15bcfeea4cb38f111be6b53eb9801f6c6becbb21025c71e9c743e04d1e35f7d14814defe",
          "sha256": "25eb822fcd9ed17b428234bf4ac5bfa75a52831db03f8b3f76d06720f56e5f42",
          "sha1": "b6f98ae03e7dadf33978853bb105c8e01a879c46",
          "md5": "09f074045b7cdf8a7f09104503a08f2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.19-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.19-SNAPSHOT-sources.jar",
          "size": 29064,
          "sha512": "ec03b71dafb50fbc7d01d0193314074cc7acfb5e1718af8d9f4de5eb39b13bf7d3479edf28f39b1ee17a55dd62d7109fd00bc715d68b37757f99ce863c90ad32",
          "sha256": "2aa3e3fc7123fe05ae05d5801c21941fa538f924a985b687713c5f0b3008e739",
          "sha1": "989c63eb2c97ffc47371aae30a46977448ca0e03",
          "md5": "10e91f1b3ffd4cb53688cd794f435826"
        }
      ]
    }
  ]
}
