{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.17-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.17-SNAPSHOT.jar",
          "size": 39473,
          "sha512": "929c8524f611f828fa4807e197a6cbad24ea6a7ea2842510c969329d8a323ee9645442722574d0874c64b9844222c3fb0e0d611b3b11012391b8b994c80de38d",
          "sha256": "bd6bb8df2c753b3347c23961929a4b090e2c0f926d417685620ea7cab17b3679",
          "sha1": "e92f8aadea23af1c2ce15faf68b608663258908a",
          "md5": "6dd308364c0838ebda6a1c72bf9f0be5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.17-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.17-SNAPSHOT.jar",
          "size": 39473,
          "sha512": "929c8524f611f828fa4807e197a6cbad24ea6a7ea2842510c969329d8a323ee9645442722574d0874c64b9844222c3fb0e0d611b3b11012391b8b994c80de38d",
          "sha256": "bd6bb8df2c753b3347c23961929a4b090e2c0f926d417685620ea7cab17b3679",
          "sha1": "e92f8aadea23af1c2ce15faf68b608663258908a",
          "md5": "6dd308364c0838ebda6a1c72bf9f0be5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.17-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.17-SNAPSHOT-sources.jar",
          "size": 29141,
          "sha512": "de1108b62da34894bf7cbc645566d46b08fa9726ee372de68e6b95e33bd0620c48df14a4b65dfd3ae9ae5a5f1cf6ee5fe2078b794adc5d23bf4d679547fee5da",
          "sha256": "09013be8a82519ff9453c72e764d34d7f1b1ddb8bbcf229bb8411c00ac4ec832",
          "sha1": "619f43f399830924e7e87d143f67c45f7f701972",
          "md5": "82c4de2f5f5aab7b7db2473be01bedda"
        }
      ]
    }
  ]
}
