{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.53.jar",
          "url": "btwr-shared-lib-0.53.jar",
          "size": 94916,
          "sha512": "b31118632276956fba6da230602b072b93d68e03864fbc076d51fec45fa021a1256dcba122745e785858d1d5a9c803fa3c0630323261e85af9d597110867a52f",
          "sha256": "14046eb44da88024b92f370515619913e046fe5d97aef9ba18754764d55630ab",
          "sha1": "f218e14ca1deee1cfce1363abda71051520121b3",
          "md5": "4ebb47ffcce616e328090ba267288bf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.53.jar",
          "url": "btwr-shared-lib-0.53.jar",
          "size": 94916,
          "sha512": "b31118632276956fba6da230602b072b93d68e03864fbc076d51fec45fa021a1256dcba122745e785858d1d5a9c803fa3c0630323261e85af9d597110867a52f",
          "sha256": "14046eb44da88024b92f370515619913e046fe5d97aef9ba18754764d55630ab",
          "sha1": "f218e14ca1deee1cfce1363abda71051520121b3",
          "md5": "4ebb47ffcce616e328090ba267288bf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.53-sources.jar",
          "url": "btwr-shared-lib-0.53-sources.jar",
          "size": 63889,
          "sha512": "3b0145e7eb7e53a76e1e565d2d5957be826bb684acb14ec15e2fef08c74a0028c66e106414e5c379c2ed02604038837407085517ae8499e6eb87421e7c3db28b",
          "sha256": "83f61e394db4b5894bf141eaf1e47990a624869e7743c1812f2f1163fd4fda2e",
          "sha1": "2a568d05180470fd1c9b574c42cd7d70f2150b09",
          "md5": "a106fc52413b79da59ddea3f24224241"
        }
      ]
    }
  ]
}
