{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "size": 20482,
          "sha512": "7f503410842fdc485a3078d27edf80dbefbe627f4a730c8cfa2ac526d2237c267eced6447c7bdfc121c46a1eef398f6a60c3e68de303771c30d2144d1b67b92d",
          "sha256": "28bc95205745e84992342d1c708a2511e255318d73169e25430860bbb75710b6",
          "sha1": "6ed69122135b218327824b98e0dd490244902a62",
          "md5": "fbdd99367e36f92b79fb010b5a2b9c64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "size": 20482,
          "sha512": "7f503410842fdc485a3078d27edf80dbefbe627f4a730c8cfa2ac526d2237c267eced6447c7bdfc121c46a1eef398f6a60c3e68de303771c30d2144d1b67b92d",
          "sha256": "28bc95205745e84992342d1c708a2511e255318d73169e25430860bbb75710b6",
          "sha1": "6ed69122135b218327824b98e0dd490244902a62",
          "md5": "fbdd99367e36f92b79fb010b5a2b9c64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT-sources.jar",
          "size": 15384,
          "sha512": "e24a3ef5fdfda528e6d85101f3ee3700f4396c1559be13cc8e1f77ac8f935625908b7632c74bdc93b1d1ee1c0ff8ef760fc9d5ed025c67209109e9174e761ddf",
          "sha256": "6b18115f9ae534944c144032392c7f1159d0e27abe56d497b49ec3c1b02d4488",
          "sha1": "34f1bd2a7f4f8aeb07caecaf235e6b54d29ccf59",
          "md5": "40532e5aaf2c9ac79278870d5e4ca72e"
        }
      ]
    }
  ]
}
