{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "size": 12836,
          "sha512": "292a94c909afdc8be7bec4c2235a70da81cc7cfa75b8125fb54a846ab1862c25ec3ade1cfe84ae5ad3b82b2b7264d35e154e0cb1802a3d44e4a5f841a951917f",
          "sha256": "f3aad195272be392a42e7590afe327b09682df4fbf130e15e85ffbbc2293115b",
          "sha1": "8c17016748a4c4c39bd5d4a5e1e9908360034bfd",
          "md5": "efabc4fc6d69070e835586df17e0e787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT.jar",
          "size": 12836,
          "sha512": "292a94c909afdc8be7bec4c2235a70da81cc7cfa75b8125fb54a846ab1862c25ec3ade1cfe84ae5ad3b82b2b7264d35e154e0cb1802a3d44e4a5f841a951917f",
          "sha256": "f3aad195272be392a42e7590afe327b09682df4fbf130e15e85ffbbc2293115b",
          "sha1": "8c17016748a4c4c39bd5d4a5e1e9908360034bfd",
          "md5": "efabc4fc6d69070e835586df17e0e787"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.7-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.7-SNAPSHOT-sources.jar",
          "size": 10627,
          "sha512": "3914c27e4243d254e698c4cb27a3f365470be7d7b04f7c7668dd99ee194e07b9bd704678ac233846fdcd09381cc1936731d734a09b85b796f039b1071b118949",
          "sha256": "797cb2d4143f94edff80032d466b6b1f1aaeff402654178f4e5d3bad14868ecf",
          "sha1": "a9b73a2dd8e59f7885dff0c55d88b43370eef41f",
          "md5": "81320105870fd6a9800ef6e2c26120e1"
        }
      ]
    }
  ]
}
