{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.45.jar",
          "url": "btwr-shared-lib-0.45.jar",
          "size": 67497,
          "sha512": "cc03fde4582b52ab625556e3e2cb7eb647b05a9daa31adbf3b63190656e8e77a44488983c8529f16cca6f4cd188fcebae97a7b5f86970e41ddb0bac3e65508fc",
          "sha256": "f84bcf6e2687e847da423a82305791febceceafa0bd5d80abd9994f76fd4b537",
          "sha1": "a1109a56adda394fcb1f7ef758b79c0f57ad15dc",
          "md5": "9df71391f38463e1e322b22a37ec44ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.45.jar",
          "url": "btwr-shared-lib-0.45.jar",
          "size": 67497,
          "sha512": "cc03fde4582b52ab625556e3e2cb7eb647b05a9daa31adbf3b63190656e8e77a44488983c8529f16cca6f4cd188fcebae97a7b5f86970e41ddb0bac3e65508fc",
          "sha256": "f84bcf6e2687e847da423a82305791febceceafa0bd5d80abd9994f76fd4b537",
          "sha1": "a1109a56adda394fcb1f7ef758b79c0f57ad15dc",
          "md5": "9df71391f38463e1e322b22a37ec44ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.45-sources.jar",
          "url": "btwr-shared-lib-0.45-sources.jar",
          "size": 48435,
          "sha512": "4200eee84319d98a9920ab82b5d2916a80ebe32f0ce61fa89ce6e94e88c66edf16336c43d3a195786497a061343e53cc0c1f43f6c9dd4eb2e9673466cba8622a",
          "sha256": "055d2b5514e7205c0c3b9919de9a1046c20c3ef257c33e4af12d824ca57ee0d0",
          "sha1": "4eeb9cc5f901f91ddaebd67652cbeaeb0e1c2261",
          "md5": "1711b5e4e52d915e6d8c28c7273b82e0"
        }
      ]
    }
  ]
}
