{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ivangeevo",
    "module": "btwr-shared-lib",
    "version": "0.30-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.30-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.30-SNAPSHOT.jar",
          "size": 58315,
          "sha512": "123670f4abaf9e63bf6667c7d1a39f53f943fef1acadca4c16b3e7c49586dbe12b64acbd1bf7b95f4bb6a9c1d9547b73059f71205a0e3d23a017c99f58d07928",
          "sha256": "6482df76552fd816dfe9f8a25322613861609e843c696504d607c4a25474b023",
          "sha1": "7c7cb2efe0b71f41361d62a674966631b11bf2bc",
          "md5": "09f032b3d8d35ae383d93bbaa77ad987"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "btwr-shared-lib-0.30-SNAPSHOT.jar",
          "url": "btwr-shared-lib-0.30-SNAPSHOT.jar",
          "size": 58315,
          "sha512": "123670f4abaf9e63bf6667c7d1a39f53f943fef1acadca4c16b3e7c49586dbe12b64acbd1bf7b95f4bb6a9c1d9547b73059f71205a0e3d23a017c99f58d07928",
          "sha256": "6482df76552fd816dfe9f8a25322613861609e843c696504d607c4a25474b023",
          "sha1": "7c7cb2efe0b71f41361d62a674966631b11bf2bc",
          "md5": "09f032b3d8d35ae383d93bbaa77ad987"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "btwr-shared-lib-0.30-SNAPSHOT-sources.jar",
          "url": "btwr-shared-lib-0.30-SNAPSHOT-sources.jar",
          "size": 40901,
          "sha512": "fd750b88aa50b461ac7d0116eaaea632b127328618300c4209fd76a01c191e22b85f01dbbe811fc23aa265c849549a23708c17a358e53065cd6f204a5513fc9e",
          "sha256": "06a48af0e9f6ce809e0b9a26832a26d2106f1d8c68f5021d7192e28cc65bb68d",
          "sha1": "6980b8cce966b918e5657630119f1de8aee8a784",
          "md5": "2a36b92288be1b167d5f3b3c42a6fb7e"
        }
      ]
    }
  ]
}
